Repository ebbba-org/ansible-role-bigbluebutton, pull requests merged in 2021-06, with the labels that each got.

#144 mongo4-ramdisk.conf: follow upstream changes from v2.3.2
  templates/mongo4-ramdisk.conf
Labels: help wanted, review needed

#146 only install certbot-repo when letsencrypt is used
  tasks/repositories.yml
Labels: help wanted, review needed

#149 add backend for html5-client according to https://docs.bigbluebutton.…
  README.md
  defaults/main.yml
  files/html5-client-log.conf
  files/html5-client-log.nginx
  tasks/installation.yml
  tasks/nginx.yml
Labels: help wanted, review needed

#147 Security suggestions
  tasks/certificate-selfsigned.yml
  tasks/freeswitch.yml
Labels: help wanted, review needed

#154 remove obsolete var, fixes #136
  README.md
  defaults/main.yml
  templates/bbb-web.properties
Labels: help wanted, review needed

#157 remove obsolete template, fixes #156
  templates/bbb-webrtc-sfu-mk.override
Labels: help wanted, review needed

#161 set LimitNOFILE depending on cpu-count
  templates/bbb-web.override
Labels: review needed

#159 set TasksMax=infinity in kurento-x.services
  templates/kurento/kurento-media-server@.service
Labels: awaiting feedback, help wanted, review needed

#140 added check for running meetings
  README.md
  defaults/main.yml
  tasks/check-for-sessions.yml
  tasks/main.yml
Labels: help wanted, review needed

#162 fix default_presentation default naming
  tasks/config.yml
Labels: review needed

#166 Fix var typo in example playbook
  README.md
Labels: review needed

#153 add sip ufw rule
  defaults/main.yml
  tasks/firewall/ufw_enable.yml
Labels: help wanted, review needed

#158 sip: play_and_get_digits moved to the defaults to make it configurable
  README.md
  defaults/main.yml
  templates/dial-in/dialplan.xml.j2
Labels: help wanted, review needed

#169 Add hotfix check for bbb_secret - this needs a proper solution
  tasks/main.yml
Labels: help wanted, review needed

#165 Add always tag to var checking and registering tasks
  tasks/main.yml
  tasks/runtimevars.yml
Labels: help wanted, review needed

#167 Handle install/uninstall coturn
  files/etc-default-coturn
  tasks/coturn.yml
  tasks/main.yml
Labels: help wanted, review needed

#134 Added bigbluebutton-exporter as Systemd service
  README.md
  defaults/main.yml
  handlers/main.yml
  tasks/checkvars.yml
  tasks/main.yml
  tasks/monitoring/all_in_one.yml
  tasks/monitoring/main.yml
  tasks/monitoring/systemd.yml
  tasks/runtimevars.yml
  templates/monitoring/bbb_exporter_secrets.env.j2
  templates/monitoring/docker-compose.yaml.j2
  templates/monitoring/monitoring.nginx.j2
Labels: help wanted, review needed

#171 Just set node command line options, fixes #170
  tasks/config.yml
Labels: review needed
