Repository ebbba-org/ansible-role-bigbluebutton, pull requests merged in 2021-05, with the labels that each got.

#122 Add sip_ip and ip for freeswitch to kurento defaults
  defaults/main.yml
Labels: help wanted

#115 feat: further bbb options from #96
  README.md
  defaults/main.yml
  tasks/config.yml
  templates/bbb-config/cron.daily/bigbluebutton
  templates/bbb-web.properties
  templates/conference.conf.xml
Labels: help wanted

#110 add the ability to set the max upload size
  README.md
  defaults/main.yml
  tasks/bbb-html5.yml
  templates/bbb-web.properties
  templates/nginx/web.nginx.j2
Labels: awaiting feedback

#128 Add bbb_allow_request_without_session
  README.md
  defaults/main.yml
  templates/bbb-web.properties
Labels: awaiting feedback, help wanted

#129 Add bbb_web_logouturl
  README.md
  defaults/main.yml
  templates/bbb-web.properties
Labels: awaiting feedback, help wanted, review needed

#132 delete duplicate var: defaultMaxUsers
  templates/bbb-web.properties
Labels: help wanted, review needed

#133 run ansible-lint on GitHub actions
  .github/workflows/ansible-lint.yaml
  tasks/bbb-html5.yml
  tasks/certificate-selfsigned.yml
  tasks/config.yml
  tasks/nginx.yml
Labels: help wanted, review needed

#130 Fix conditional vars in docker_login task
  tasks/docker.yml
Labels: help wanted, review needed
