Repository ebbba-org/ansible-role-bigbluebutton, pull requests merged in 2021-11, with the labels that each got.

#255 Fix kurento tasks nonbreaking
  handlers/main.yml
  tasks/kurento.yml
  templates/bbb-webrtc-sfu.override
  templates/kurento/kurento-media-server.service.tpl
  templates/kurento/kurento-media-server.target
Labels: review needed

#249 Start chrony if bbb_ntp_cron is reset to false, fixes #248
  tasks/ntp.yml
Labels: review needed

#267 For an initial ansible-run, tasks need to be reordered; fix #265
  README.md
  tasks/config.yml
  templates/bbb-config/bbb-apps-akka.conf.j2
  templates/bbb-config/bbb-fsesl-akka.conf.j2
  templates/bbb-config/bbb-web.properties.j2
Labels: bug, review needed

#266 @Wilkis3 selectable bbb version - PR214
  README.md
  defaults/main.yml
  tasks/repositories.yml
Labels: enhancement, review needed

#268 BigBlueButton 2.4 Add option to disable/enable the Learning Dashboard Feature
  README.md
  defaults/main.yml
  templates/bbb-config/bbb-web.properties.j2
Labels: enhancement, review needed

#270 [Security] Set Freeswitch default password, Checkvars step, README
  README.md
  defaults/main.yml
  tasks/checkvars.yml
  tasks/freeswitch.yml
Labels: bug

#269 Juju4 devel 23b - PR #182
  .github/workflows/full_deployment.yml
  molecule/default/converge.yml
  molecule/default/molecule.yml
  molecule/default/verify.yml
  tasks/repositories.yml
  templates/freeswitch/freeswitch_apparmor_profile
  test/integration/default-mongo36/bats/idempotency.bats
  test/integration/default-mongo36/default.yml
  test/integration/default-mongo36/serverspec/Gemfile
  test/integration/default-mongo36/serverspec/Rakefile
  test/integration/default-mongo36/serverspec/bbb_spec.rb
  test/integration/default-mongo36/serverspec/mongo_spec.rb
  test/integration/default-mongo36/serverspec/redis_spec.rb
  test/integration/default-mongo36/serverspec/webserver_spec.rb
  test/integration/default-mongo4/bats/idempotency.bats
  test/integration/default-mongo4/default.yml
  test/integration/default-mongo4/serverspec/Gemfile
  test/integration/default-mongo4/serverspec/Rakefile
  test/integration/default-mongo4/serverspec/bbb_spec.rb
  test/integration/default-mongo4/serverspec/mongo_spec.rb
  test/integration/default-mongo4/serverspec/redis_spec.rb
  test/integration/default-mongo4/serverspec/webserver_spec.rb
  test/integration/default-node10/default.yml
  test/integration/default-node12/bats/idempotency.bats
  test/integration/default-node12/default.yml
  test/integration/default-node12/serverspec/Gemfile
  test/integration/default-node12/serverspec/Rakefile
  test/integration/default-node12/serverspec/bbb_spec.rb
  test/integration/default-node12/serverspec/mongo_spec.rb
  test/integration/default-node12/serverspec/redis_spec.rb
  test/integration/default-node12/serverspec/webserver_spec.rb
  test/integration/default/default.yml
  test/integration/example.crt
  test/integration/example.key
Labels: enhancement, review needed

#264 use bbb_default_logo_url as branding image setting
  tasks/greenlight.yml
Labels: enhancement
