Repository ebbba-org/ansible-role-bigbluebutton, pull requests merged in 2022-06, with the labels that each got.

#311 Prevent corrupted /dev/shm/core.db errors.
  tasks/freeswitch.yml
Labels: enhancement

#310 Revert upstream freeswitch jitterbuffer experiments
  tasks/freeswitch.yml
Labels: enhancement

#315 Do not use `bufferChatInsertsMs` with BBB 2.5
  README.md
Labels: documentation

#314 fix issue #313, remove need for acme.sh --force
  defaults/main.yml
  tasks/certificate-letsencrypt.yml
Labels: enhancement

#312 fix issue #309 when systemd-timesyncd is already disabled
  tasks/ntp.yml
Labels: bug

#317 Fixed order of imports to prevent fail of creating /etc/bigbluebutton…
  tasks/config.yml
  tasks/nginx.yml
Labels: bug
