Repository ebbba-org/ansible-role-bigbluebutton, pull requests merged in 2023-04, with the labels that each got.

#350 Feature merge 2.5 to 2.6
  .ansible-lint
  .kitchen.yml
  .travis.yml
  README.md
  defaults/main.yml
  handlers/main.yml
  meta/main.yml
  tasks/bbb-html5.yml
  tasks/bbb-web.yml
  tasks/bbb_secret.yml
  tasks/certificate-custom.yml
  tasks/certificate-letsencrypt.yml
  tasks/certificate.yml
  tasks/check-for-sessions.yml
  tasks/checkvars.yml
  tasks/config.yml
  tasks/dial-in/remove.yml
  tasks/dial-in/setup.yml
  tasks/docker.yml
  tasks/etherpad.yml
  tasks/firewall/ufw_enable.yml
  tasks/freeswitch.yml
  tasks/installation.yml
  tasks/kurento.yml
  tasks/locale.yml
  tasks/main.yml
  tasks/mongodb.yml
  tasks/monitoring/all_in_one.yml
  tasks/monitoring/main.yml
  tasks/monitoring/systemd.yml
  tasks/nginx.yml
  tasks/ntp.yml
  tasks/repositories.yml
  tasks/stun-turn.yml
  tasks/webrtc-sfu.yml
  templates/bbb-config/cron.daily/bigbluebutton
Labels: enhancement

#351 Fix collecting bbb_secret if bbb isn't installed
  tasks/bbb_secret.yml
Labels: bug

#349 Add cluster proxy configuration
  README.md
  defaults/main.yml
  tasks/bbb-html5.yml
  tasks/bbb-web.yml
  tasks/checkvars.yml
  tasks/config.yml
  tasks/etherpad.yml
  templates/bbb-web/bbb-web.properties.j2
Labels: feature

#352 Revert "Path to images has changed"
  defaults/main.yml
  tasks/config.yml
Labels: bug
